#! /bin/sh

lemonbuddy_terminate noconfirm
lemonbuddy_wrapper top &

bspc config border_width         5
bspc config window_gap          10
bspc config top_padding         30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config center_pseudo_tiled  true

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc monitor -d I II III IV V

#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
